# Generated by Django 4.2.9 on 2025-12-18 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_githubaccount_githubrepository'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.BigIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webhook', to='core.githubrepository')),
            ],
            options={
                'db_table': 'github_webhooks',
            },
        ),
    ]
