# Generated by Django 4.2.9 on 2025-12-18 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_githubwebhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubaccount',
            name='scopes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='GitHubWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('delivery_id', models.CharField(max_length=100, unique=True)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='core.githubrepository')),
            ],
            options={
                'db_table': 'github_webhook_events',
                'ordering': ['-received_at'],
            },
        ),
    ]
